CREATE TABLE IF NOT EXISTS users (
    user_id CHAR(38) PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    user_email VARCHAR(90) NOT NULL,
    user_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
